### ISSUE TITLE
Failure to Add payment method

### ISSUE THREAD

**Issue by vlightyear** [killbill/killbill-cybersource-plugin#18]
Hello,

I'm using killbill-cybersource 5.2.2 and killbill 0.18.10 when I try to add a payment method to an account, I receive the following error:
`{"className":"org.killbill.billing.payment.api.PaymentApiException","code":7005,"message":"Failed to add payment method for account ca719787-dac0-4569-9333-5d6579bee936 : (<unknown>): sequence entries are not allowed here at line 1 column 15","causeClassName":null,"causeMessage":null,"stackTrace":[]}ubuntu@ip-172-31-5-83:~/platform/killbill$ {"className":"org.killbill.billing.payme9-9333-5d6579bee936 : (<unknown>): sequence entries are not allowed here at line 1 column 15","causeClassName":null,"causeMessage":null,"stackTrace":[]}
`

And here is the output from the killbill console:

` < Content-Type: application/json
62 <

2017-06-21T13:35:31,426+0000 lvl='INFO', log='LoggingFilter', th='http-bio-9443-exec-5', xff='', rId='5d1fd2a0-5468-43df-bd62-ec6a1b4b4ce7', aRId='', tRId='1', 63 * Server in-bound request
63 > POST http://127.0.0.1:9443/1.0/kb/accounts/ca719787-dac0-4569-9333-5d6579bee936/paymentMethods?isDefault=true&pluginProperty=skip_gw=true
63 > host: 127.0.0.1:9443
63 > authorization: Basic YWRtaW46cGFzc3dvcmQ=
63 > user-agent: curl/7.47.0
63 > accept: */*
63 > x-killbill-apikey: ******
63 > x-killbill-apisecret: ***********
63 > x-killbill-createdby: admin
63 > content-type: application/json
63 > content-length: 977
63 >

2017-06-21T13:35:31,680+0000 lvl='WARN', log='KillbillLogWriter', th='Thread-10', xff='', rId='5d1fd2a0-5468-43df-bd62-ec6a1b4b4ce7', aRId='1', tRId='1', [cybersource-plugin] Failure in add_payment_method: (<unknown>): sequence entries are not allowed here at line 1 column 15
org/jruby/ext/psych/PsychParser.java:215:in `parse'
classpath:/META-INF/jruby.home/lib/ruby/shared/psych.rb:205:in `parse_stream'
classpath:/META-INF/jruby.home/lib/ruby/shared/psych.rb:153:in `parse'
classpath:/META-INF/jruby.home/lib/ruby/shared/psych.rb:129:in `load'
/var/tmp/bundles/plugins/ruby/killbill-cybersource/5.2.2/ROOT/gems/gems/killbill-8.3.2/lib/killbill/helpers/active_merchant/configuration.rb:112:in `get_tenant_config'
/var/tmp/bundles/plugins/ruby/killbill-cybersource/5.2.2/ROOT/gems/gems/killbill-8.3.2/lib/killbill/helpers/active_merchant/configuration.rb:37:in `gateways'
/var/tmp/bundles/plugins/ruby/killbill-cybersource/5.2.2/ROOT/gems/gems/killbill-8.3.2/lib/killbill/helpers/active_merchant/payment_plugin.rb:583:in `lookup_gateway'
/var/tmp/bundles/plugins/ruby/killbill-cybersource/5.2.2/ROOT/gems/gems/killbill-8.3.2/lib/killbill/helpers/active_merchant/payment_plugin.rb:159:in `add_payment_method'
/var/tmp/bundles/plugins/ruby/killbill-cybersource/5.2.2/ROOT/lib/cybersource/api.rb:218:in `add_payment_method'
/var/tmp/bundles/plugins/ruby/killbill-cybersource/5.2.2/ROOT/gems/gems/killbill-8.3.2/lib/killbill/gen/plugin-api/payment_plugin_api.rb:443:in `addPaymentMethod'
Killbill$$Plugin$$Api$$PaymentPluginApi_1555657243.gen:13:in `addPaymentMethod'
2017-06-21T13:35:31,729+0000 lvl='WARN', log='LoggingResponse', th='http-bio-9443-exec-5', xff='', rId='5d1fd2a0-5468-43df-bd62-ec6a1b4b4ce7', aRId='1', tRId='1', Bad request
org.killbill.billing.payment.api.PaymentApiException: Failed to add payment method for account ca719787-dac0-4569-9333-5d6579bee936 : (<unknown>): sequence entries are not allowed here at line 1 column 15
        at org.killbill.billing.payment.core.PaymentMethodProcessor$1.doOperation(PaymentMethodProcessor.java:141)
        at org.killbill.billing.payment.core.PaymentMethodProcessor$1.doOperation(PaymentMethodProcessor.java:114)
        at org.killbill.billing.payment.core.ProcessorBase$WithAccountLock.processAccountWithLock(ProcessorBase.java:179)
        at org.killbill.billing.payment.core.ProcessorBase$CallableWithAccountLock.call(ProcessorBase.java:162)
        at org.killbill.billing.payment.core.ProcessorBase$CallableWithAccountLock.call(ProcessorBase.java:143)
        at org.killbill.billing.payment.dispatcher.CallableWithRequestData.call(CallableWithRequestData.java:69)
        at org.killbill.commons.concurrent.WrappedCallable.call(WrappedCallable.java:42)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.killbill.commons.concurrent.WrappedRunnable.run(WrappedRunnable.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-06-21T13:35:31,740+0000 lvl='INFO', log='LoggingFilter', th='http-bio-9443-exec-5', xff='', rId='5d1fd2a0-5468-43df-bd62-ec6a1b4b4ce7', aRId='1', tRId='1', 63 * Server out-bound response
63 < 400
63 < Content-Type: application/json
63 <
`
The API key and secret have been obscured.

What could be the cause of this?

**Comment by pierre** [comment]
It looks like the configuration is invalid (bad YAML uploaded).

Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead if you still have issues after fixing the config. See https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md for reporting issues.
